### ISSUE TITLE
Problem with Python data layer

### ISSUE THREAD

**Issue by sivalley** [lluisgomez/TextTopicNet#2]
Thank you for the excellent paper & code. Every step works until it reaches Caffe Python data layer. May I know which version of Caffe and Google protobuf did you use? I am getting errors with the latest versions on their Github repositories...

**Comment by yash0307** [comment]
Caffe version: '1.0.0-rc5'
libprotoc 3.2.0

Can you provide the exact error message ?

**Comment by sivalley** [comment]
Hi Mr. Patel,

Thank you for replying. Since 5 months have passed, I don’t remember the message anymore. 

I have given up on using Caffe with Python data layer and moved to Tensorflow...
