### ISSUE TITLE
LDA model

### ISSUE THREAD

**Issue by ybh16** [lluisgomez/TextTopicNet#4]
When I trained the LDA model, I found that the model was larger than the  website', and when I used them in multi_modal_retrieval.py, it occurs" IndexError: index 116494 is out of bounds for axis 1 with size 100000", why?

**Comment by yash0307** [comment]
Can you provide more specific details as to which line of code this error is occurring on ?

My guess is that you are using a different dictionary for obtaining BoW representations for text documents. Usual idea is to ignore very infrequent words (which is what we did while generating the dictionary).

**Comment by irazakharchenko** [comment]
Hi!
I have the same error it's this line:
`lda_vector = ldamodel.get_document_topics(bow_vector, minimum_probability=None)`

**Comment by yash0307** [comment]
@irazakharchenko, can you confirm that the dictionary of words provided in the repository was used for generating the bag of words vector (bow_vector) ?

**Comment by irazakharchenko** [comment]
@yash0307, no, I created it myself using generate_train_dict.py.
