### ISSUE TITLE
Folder is missing

### ISSUE THREAD

**Issue by irazakharchenko** [lluisgomez/TextTopicNet#5]
Hi,

Congratulations on your work "Self-supervised learning of visual 
features through embedding images into text topic spaces"!

We are trying to reproduce your experiments using your GitHub directory. 
However, we cannot find the following files required in 
voc_2007_classification.py:

gt_root = 
'/home/yash/LDA_wikipedia_imageCLEF/wiki_large/TextTopicNet/nets/CaffeNet/SVMs/VOC2007/GT_labels/'
gt_train_sufix = '_train.txt'
gt_val_sufix = '_val.txt'
gt_test_sufix = '_test.txt'

Can you please provide us with those files?

**Comment by yash0307** [comment]
Hello,

Thanks for appreciating our work.

This folder corresponds to the PASCAL VOC 2007 dataset used for the evaluation of learned visual features on image classification task.

You can download this dataset from this link: http://host.robots.ox.ac.uk/pascal/VOC/voc2007/index.html

Once the download is done, please specify the path as per location on your device to "gt_root" variable.
